"""Read-side API used by the PWA."""
from collections import defaultdict
from datetime import date as _date, datetime, time, timedelta, timezone
from zoneinfo import ZoneInfo

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response
from starlette.concurrency import run_in_threadpool
from sqlalchemy import and_, desc, func, or_, select
from sqlalchemy.orm import Session, joinedload

from db.models import (
    NOT_A_BIRD_LABEL,
    POOR_QUALITY_LABEL,
    SENTINEL_LABELS,
    Correction,
    Detection,
    Species,
    Visit,
)
from db.session import get_db
from pipeline.fuse import get_recent_audio_species
from pipeline.process import CROPS_DIR
from settings import settings

# Sentinels we hide from the default feed: things the user has explicitly
# said are not real-bird-sightings the feed should surface. NAB (false
# positive) and Poor Quality (unidentifiable crop) both retire the row
# from the browsing view. Unknown bird is intentionally NOT here — it
# IS a real bird, just species-unspecified, and the user wants to see
# it in the feed.
HIDDEN_FROM_FEED = frozenset({NOT_A_BIRD_LABEL, POOR_QUALITY_LABEL})

router = APIRouter()


def _tz() -> ZoneInfo:
    return ZoneInfo(settings.camera_timezone)


def _camera_tz_offset_str() -> str:
    offset = datetime.now(_tz()).strftime("%z")
    return f"{offset[:3]}:{offset[3:]}"


def _local_day_bounds(target: _date) -> tuple[datetime, datetime]:
    """Naive-UTC half-open bounds [start, end) for one camera-local calendar day."""
    tz = _tz()
    start_local = datetime.combine(target, time.min, tzinfo=tz)
    end_local = start_local + timedelta(days=1)
    return (
        start_local.astimezone(timezone.utc).replace(tzinfo=None),
        end_local.astimezone(timezone.utc).replace(tzinfo=None),
    )


def _parse_cursor(cursor: str) -> tuple[datetime, int]:
    """Decode a 'captured_at_iso|detection_id' cursor string."""
    try:
        ts_str, id_str = cursor.split("|", 1)
        return datetime.fromisoformat(ts_str), int(id_str)
    except (ValueError, AttributeError) as exc:
        raise HTTPException(status_code=400, detail=f"Invalid cursor: {cursor}") from exc


@router.get("")
async def list_detections(
    limit: int = Query(50, ge=1, le=200),
    species_id: int | None = Query(None, description="Filter to one species (by id)"),
    species_name: str | None = Query(None, description="Filter to one species (by common name — convenience for the picker which speaks names)"),
    include_not_a_bird: bool = Query(False, description="Include detections corrected to 'Not a bird'"),
    only_not_a_bird: bool = Query(False, description="Show ONLY detections corrected to 'Not a bird' — for reviewing/correcting prior NAB labels"),
    only_unidentified: bool = Query(False, description="Show ONLY detections with no species assigned (the classifier rejected; awaiting user label)"),
    interesting: bool = Query(
        False,
        description="Hide common 'junk' feeder birds — pigeons, Mourning Doves, "
        "and sparrows (all sparrow species + the 'Sparrow' family label). "
        "Matched by common name so any sparrow/pigeon species is covered. "
        "Unidentified crops (no species yet) are kept — they might be anything. "
        "Composes with the default NAB/Poor-Quality hiding.",
    ),
    awaiting_review: bool = Query(
        False,
        description="Show ONLY detections the classifier labeled but the user hasn't "
        "reviewed yet — species_id IS NOT NULL and no Correction row exists. Drives the "
        "'Awaiting review' feed filter that measures true positives.",
    ),
    source: str | None = Query(
        None,
        description="Filter to detections whose Correction was generated by this source "
        "(e.g. `llm-claude`). Used by the LLM-review feed to bulk-spot-check Claude's labels.",
    ),
    binary_nab: bool = Query(
        False,
        description="Show ONLY detections the binary post-filter overrode to "
        "'Not a bird' (nab_override_p IS NOT NULL). Audits the filter's "
        "precision — each card still carries the species the classifier wanted "
        "in raw_predictions, so you can spot real birds it wrongly killed and "
        "re-correct them. Bypasses the default NAB-hiding.",
    ),
    bad_quality: bool = Query(
        False,
        description="Show ONLY detections flagged as low-quality by any of the "
        "per-crop metrics: small (max bbox dim < 80 px), dark (mean grayscale "
        "< 30), or blurry (Laplacian variance < 30). Compose with other filters "
        "(e.g. awaiting_review=true AND bad_quality=true to triage the worst "
        "candidates first).",
    ),
    min_sharpness: float | None = Query(
        None,
        description="Numeric lower bound on Laplacian-variance sharpness. Use "
        "with a negative sign for the inverse — e.g. set bad_quality=true to get "
        "the standard 'is blurry' threshold of <30, or pass min_sharpness=100 to "
        "see only crisper-than-average crops.",
    ),
    diversity: bool = Query(
        False,
        description="Diversity-First mode: returns the single best crop per species per day, "
        "with daily_count of sightings for that species on that day.",
    ),
    before: str | None = Query(
        None,
        description="Cursor for pagination, format: '<captured_at_iso>|<detection_id>'. "
        "Returns rows captured strictly before this point. The detection id is the "
        "tiebreaker for visits that share a started_at value.",
    ),
    db: Session = Depends(get_db),
) -> list[dict]:
    # Sort by CAPTURE time (Visit.started_at, parsed from the Reolink filename),
    # NOT by processing time (Detection.created_at / id). During a backlog drain
    # these can differ by many hours — an old visit just processed shouldn't pop
    # to the top of the feed. Detection.id desc as a tiebreaker keeps the order
    # deterministic when multiple visits share a started_at second.
    daily_counts: dict[int, int] = {}
    if diversity:
        tz_offset = _camera_tz_offset_str()
        day_expr = func.date(Visit.started_at, tz_offset)
        quality_expr = func.coalesce(Detection.sharpness, 0) * func.coalesce(Detection.crop_area_px, 0)

        ranked_sub = (
            select(
                Detection.id.label("det_id"),
                func.row_number().over(
                    partition_by=[Detection.species_id, day_expr],
                    order_by=[Detection.confidence.desc(), quality_expr.desc(), Detection.id.desc()],
                ).label("rn"),
                func.count().over(
                    partition_by=[Detection.species_id, day_expr],
                ).label("daily_count"),
            )
            .join(Visit, Detection.visit_id == Visit.id)
            .where(Detection.species_id.isnot(None))
            .subquery()
        )

        q = (
            db.query(Detection, ranked_sub.c.daily_count)
            .join(ranked_sub, Detection.id == ranked_sub.c.det_id)
            .join(Visit, Detection.visit_id == Visit.id)
            .options(joinedload(Detection.species), joinedload(Detection.visit))
            .filter(ranked_sub.c.rn == 1)
        )
        if species_id is None and species_name is None:
            # Diversity-First feed guard: suppress 1-off unconfirmed sightings
            # with low confidence (< 0.60) from dominating the feed.
            # Liberal audio confirmation: species heard today or in the past
            # month count as confirmed and are included.
            recent_audio = get_recent_audio_species(db)
            recent_sp_ids = (
                {row[0] for row in db.query(Species.id).filter(Species.common_name.in_(recent_audio)).all()}
                if recent_audio
                else set()
            )
            audio_cond = Detection.audio_confirmed.is_(True)
            if recent_sp_ids:
                audio_cond = or_(audio_cond, Detection.species_id.in_(recent_sp_ids))

            q = q.filter(
                or_(
                    ranked_sub.c.daily_count > 1,
                    audio_cond,
                    Detection.confidence >= 0.60,
                )
            )
        q = q.order_by(desc(Visit.started_at), desc(Detection.id))
    else:
        q = (
            db.query(Detection)
            .join(Visit, Detection.visit_id == Visit.id)
            .options(joinedload(Detection.species), joinedload(Detection.visit))
            .order_by(desc(Visit.started_at), desc(Detection.id))
        )
    if species_id is not None:
        q = q.filter(Detection.species_id == species_id)
    if species_name is not None:
        # Resolve name → id once; if no Species row exists yet for this name
        # (the picker can offer names not yet in the DB), return an empty
        # result instead of erroring — semantically "no detections of that".
        sp = db.query(Species).filter(Species.common_name == species_name).one_or_none()
        if sp is None:
            return []
        q = q.filter(Detection.species_id == sp.id)
    if only_unidentified:
        # The "show me the queue I need to label" filter.
        q = q.filter(Detection.species_id.is_(None))
    species_joined = False
    if only_not_a_bird:
        # NAB-review mode: show ONLY 'Not a bird'-labeled detections so the
        # user can scan past mistakes and re-correct them. include_not_a_bird
        # is ignored in this mode (we're explicitly opting INTO NAB).
        q = q.join(Species, Detection.species_id == Species.id).filter(
            Species.common_name == NOT_A_BIRD_LABEL
        )
        species_joined = True
    elif not include_not_a_bird and not binary_nab:
        # Default feed: hide NAB and Poor-Quality detections so the feed
        # shows only real, identifiable birds. The rows still exist in
        # the DB for the retraining pipeline (NAB as negatives,
        # Poor Quality as explicit drop-from-training samples).
        # binary_nab opts INTO NAB (it audits exactly those), so it skips
        # this hide — same shape as only_not_a_bird above.
        q = q.outerjoin(Species, Detection.species_id == Species.id).filter(
            (Species.common_name.is_(None))
            | (~Species.common_name.in_(HIDDEN_FROM_FEED))
        )
        species_joined = True
    if interesting:
        # "Interesting birds" feed: screen out the high-volume feeder regulars
        # the user considers junk. Substring matches on the common name so we
        # catch every sparrow species (and the 'Sparrow' family label) and any
        # pigeon without enumerating them. Rows with no species yet
        # (Unidentified) have a NULL common_name and are kept — an unlabeled
        # crop could be anything.
        if not species_joined:
            q = q.outerjoin(Species, Detection.species_id == Species.id)
            species_joined = True
        junk = or_(
            Species.common_name.ilike("%sparrow%"),
            Species.common_name.ilike("%pigeon%"),
            Species.common_name == "Mourning Dove",
        )
        q = q.filter(or_(Species.common_name.is_(None), ~junk))
    if binary_nab:
        # The binary-filter audit cohort: only crops it overrode to NAB.
        q = q.filter(Detection.nab_override_p.isnot(None))
    if source is not None:
        # Restrict to detections whose LATEST Correction was generated by
        # the given source. Used by the "LLM-labeled" review filter so the
        # user can scan Claude's labels and override the wrong ones.
        #
        # Latest, not any: a detection the user has since corrected or
        # confirmed grows a newer Correction row, and the older LLM row —
        # where pre-retire-mechanism legacy data still has one — must not
        # drag the detection back into the review queue. This must stay in
        # lockstep with the corrections_by_det pick below, which is what
        # the card UI keys its review affordances on.
        latest_correction_source = (
            select(Correction.source)
            .where(Correction.detection_id == Detection.id)
            .order_by(Correction.created_at.desc(), Correction.id.desc())
            .limit(1)
            .scalar_subquery()
        )
        q = q.filter(latest_correction_source == source)
    if bad_quality:
        # "Bad crop" filter: any of the three quality dimensions trips.
        # Thresholds (small/dark/blurry) are intentionally lenient — we
        # want to surface the rough triage pool, not a precise rejection
        # set. Min-quality compositions (min_sharpness etc.) are the more
        # precise tool. NULL values on legacy rows are NOT flagged as bad
        # (no quality info means "unknown," don't surface accidentally).
        q = q.filter(or_(
            Detection.crop_area_px < 80 * 80,
            Detection.brightness < 30,
            Detection.sharpness < 30,
        ))
    if min_sharpness is not None:
        q = q.filter(Detection.sharpness >= min_sharpness)
    if awaiting_review:
        # Classifier produced a label, user hasn't acted on it yet.
        # We can't measure true-positive rate without this — every
        # Correction today is implicitly "user disagreed," so the
        # classifier_accuracy metric is selection-biased to ~0%. This
        # filter surfaces the unreviewed pool so the user can ✓ Confirm
        # (records agreement) or ✏️ Change / 🚫 NAB (existing paths).
        q = q.outerjoin(Correction, Correction.detection_id == Detection.id).filter(
            Detection.species_id.isnot(None),
            Correction.id.is_(None),
        )
    if before is not None:
        # Compound cursor: row "comes before" the cursor iff its (started_at, id)
        # is lexicographically smaller in our DESC ordering.
        cur_ts, cur_id = _parse_cursor(before)
        q = q.filter(
            or_(
                Visit.started_at < cur_ts,
                and_(Visit.started_at == cur_ts, Detection.id < cur_id),
            )
        )
    if diversity:
        results = q.limit(limit).all()
        rows = [r[0] for r in results]
        daily_counts = {r[0].id: int(r[1]) for r in results}
    else:
        rows = q.limit(limit).all()

    # Look up Correction.{source,rationale} for each detection in the page
    # in one shot — we want to surface a small "✨ Claude says: ..." line
    # on the card whenever the label came from an LLM. We don't join in
    # the SQL above because the user can disable the source filter and
    # still want this metadata.
    det_ids = [d.id for d in rows]
    corrections_by_det: dict[int, Correction] = {}
    if det_ids:
        for c in db.query(Correction).filter(Correction.detection_id.in_(det_ids)).all():
            existing = corrections_by_det.get(c.detection_id)
            if existing is None or (
                (c.created_at or datetime.min, c.id)
                > (existing.created_at or datetime.min, existing.id)
            ):
                corrections_by_det[c.detection_id] = c

    # Look up pair sightings (visits with both a male and female of the same species)
    pair_keys: set[tuple[int, int]] = set()
    visit_ids = [d.visit_id for d in rows if d.visit_id]
    if visit_ids:
        sex_rows = (
            db.query(Detection.visit_id, Detection.species_id, Detection.sex)
            .filter(
                Detection.visit_id.in_(visit_ids),
                Detection.sex.isnot(None),
                Detection.species_id.isnot(None),
            )
            .all()
        )
        visit_sexes: dict[tuple[int, int], set[str]] = defaultdict(set)
        for vid, spid, s in sex_rows:
            if s:
                visit_sexes[(vid, spid)].add(s)
        pair_keys = {k for k, sexes in visit_sexes.items() if "male" in sexes and "female" in sexes}

    return [
        {
            "id": d.id,
            "visit_id": d.visit_id,
            # species_id lets the PWA link cards to the /species/:id plate.
            "species_id": d.species_id,
            "species": d.species.common_name if d.species else None,
            "scientific_name": d.species.scientific_name if d.species else None,
            "sex": d.sex,
            "is_pair": (d.visit_id, d.species_id) in pair_keys if (d.visit_id and d.species_id) else False,
            # Wikipedia thumbnail surfaced on review-mode cards so the user
            # can compare their crop against a clean reference photo. NULL
            # for sentinels / families / un-fetched species.
            "reference_image_url": d.species.reference_image_url if d.species else None,
            "confidence": d.confidence,
            "audio_confirmed": bool(d.audio_confirmed),
            "raw_predictions": d.raw_predictions,
            "crop_url": f"/media/{d.crop_path}",
            "bbox": d.bbox,
            "track_id": d.track_id,
            "captured_at": d.visit.started_at.isoformat() if d.visit else d.created_at.isoformat(),
            "created_at": d.created_at.isoformat(),
            "cursor": f"{(d.visit.started_at if d.visit else d.created_at).isoformat()}|{d.id}",
            "daily_count": daily_counts.get(d.id, 1),
            # New fields for spot-checking LLM-generated labels. Both
            # null on legacy / user-via-UI corrections.
            "correction_source": (corrections_by_det.get(d.id).source if corrections_by_det.get(d.id) else None),
            "correction_rationale": (corrections_by_det.get(d.id).rationale if corrections_by_det.get(d.id) else None),
            # Per-crop quality metrics. NULL on legacy rows that haven't
            # been backfilled. Frontend uses these for the per-card score
            # footer and the "bad crops" filter chip.
            "crop_area_px": d.crop_area_px,
            "brightness": d.brightness,
            "sharpness": d.sharpness,
            # P(NAB) the binary filter scored, non-null only when it overrode
            # this crop to "Not a bird". Lets the UI flag/sort the audit cohort.
            "nab_override_p": d.nab_override_p,
            "has_lucky": bool(
                d.visit_id is not None
                and d.track_id is not None
                and (CROPS_DIR / f"v{d.visit_id:08d}_t{d.track_id:04d}_initial_raw.jpg").exists()
            ),
            "has_sr": bool(
                d.visit_id is not None
                and d.track_id is not None
                and (CROPS_DIR / f"v{d.visit_id:08d}_t{d.track_id:04d}_sr.jpg").exists()
            ),
            "has_sisr": bool(
                d.visit_id is not None
                and d.track_id is not None
                and (CROPS_DIR / f"v{d.visit_id:08d}_t{d.track_id:04d}_sisr.jpg").exists()
            ),
        }
        for d in rows
    ]


@router.get("/daily_story")
async def get_daily_story(
    target_date: str | None = Query(None, description="ISO date YYYY-MM-DD (defaults to camera-local today)"),
    db: Session = Depends(get_db),
) -> dict:
    tz = _tz()
    today_local = datetime.now(tz).date()

    if target_date:
        try:
            target = _date.fromisoformat(target_date)
        except ValueError as exc:
            raise HTTPException(status_code=400, detail="Invalid date format, expected YYYY-MM-DD") from exc
        is_today = (target == today_local)
    else:
        target = today_local
        is_today = True

    start_utc, end_utc = _local_day_bounds(target)

    # Fetch detections for the day
    dets = (
        db.query(Detection)
        .join(Visit, Detection.visit_id == Visit.id)
        .join(Species, Detection.species_id == Species.id)
        .filter(Visit.started_at >= start_utc, Visit.started_at < end_utc)
        .filter(~Species.common_name.in_(HIDDEN_FROM_FEED))
        .options(joinedload(Detection.species), joinedload(Detection.visit))
        .all()
    )

    fallback_date: str | None = None
    if not target_date and not dets:
        latest_visit = (
            db.query(Visit.started_at)
            .join(Detection, Detection.visit_id == Visit.id)
            .join(Species, Detection.species_id == Species.id)
            .filter(~Species.common_name.in_(HIDDEN_FROM_FEED))
            .order_by(Visit.started_at.desc())
            .first()
        )
        if latest_visit and latest_visit[0]:
            fallback_target = latest_visit[0].replace(tzinfo=timezone.utc).astimezone(tz).date()
            if fallback_target != target:
                fallback_date = fallback_target.isoformat()
                fb_start, fb_end = _local_day_bounds(fallback_target)
                start_utc, end_utc = fb_start, fb_end
                dets = (
                    db.query(Detection)
                    .join(Visit, Detection.visit_id == Visit.id)
                    .join(Species, Detection.species_id == Species.id)
                    .filter(Visit.started_at >= fb_start, Visit.started_at < fb_end)
                    .filter(~Species.common_name.in_(HIDDEN_FROM_FEED))
                    .options(joinedload(Detection.species), joinedload(Detection.visit))
                    .all()
                )
                target = fallback_target
                is_today = False

    if not dets:
        return {
            "date": target.isoformat(),
            "is_today": is_today,
            "has_data": False,
            "fallback_date": fallback_date,
            "total_visits": 0,
            "total_detections": 0,
            "species_count": 0,
            "hero": None,
            "species_highlights": [],
        }

    species_map: dict[int, list[Detection]] = defaultdict(list)
    for d in dets:
        if d.species_id:
            species_map[d.species_id].append(d)

    resident_names = {"Mourning Dove", "Rock Pigeon", "House Sparrow", "Sparrow"}
    recent_audio = get_recent_audio_species(db, when=end_utc)

    def _score_det(d: Detection) -> float:
        conf = d.confidence or 0.0
        sharp_norm = min((d.sharpness or 0.0) / 1000.0, 1.0)
        sp_name = d.species.common_name if d.species else ""
        is_res = bool(sp_name in resident_names)
        is_audio = bool(d.audio_confirmed) or (sp_name in recent_audio)
        # Rarity bonus is only earned by reliable sightings (high confidence or audio confirmed)
        if not is_res and (conf >= 0.70 or is_audio):
            rarity_bonus = 0.20
        elif is_res:
            rarity_bonus = 0.05
        else:
            rarity_bonus = 0.0
        return conf * 0.40 + sharp_norm * 0.40 + rarity_bonus

    # Eligible hero candidate pool: require confidence >= 0.60 or audio confirmation to be eligible
    eligible_hero_dets = [
        d for d in dets
        if d.audio_confirmed or ((d.species.common_name if d.species else "") in recent_audio) or (d.confidence or 0.0) >= 0.60
    ]
    hero_det = max(eligible_hero_dets or dets, key=_score_det)

    highlights = []
    for sp_id, group in species_map.items():
        best = max(group, key=lambda d: (d.confidence, (d.sharpness or 0) * (d.crop_area_px or 0)))
        sp_name = best.species.common_name if best.species else "Unknown"
        is_res = sp_name in resident_names
        is_audio = any(d.audio_confirmed for d in group) or (sp_name in recent_audio)
        # Guard against 1-off unconfirmed non-resident low confidence sightings in the highlights gallery
        if not is_res and not is_audio and len(group) == 1 and (best.confidence or 0.0) < 0.60:
            continue
        highlights.append({
            "species_id": sp_id,
            "common_name": sp_name,
            "scientific_name": best.species.scientific_name if best.species else "",
            "count": len(group),
            "best_detection_id": best.id,
            "best_crop_url": f"/media/{best.crop_path}",
            "confidence": best.confidence,
            "sharpness": best.sharpness,
            "captured_at": (best.visit.started_at if best.visit else best.created_at).isoformat(),
            "is_resident": is_res,
        })

    highlights.sort(key=lambda h: (h["is_resident"], -h["count"]))

    hero_dict = {
        "id": hero_det.id,
        "species": hero_det.species.common_name if hero_det.species else "Unknown",
        "scientific_name": hero_det.species.scientific_name if hero_det.species else "",
        "confidence": hero_det.confidence,
        "sharpness": hero_det.sharpness,
        "crop_url": f"/media/{hero_det.crop_path}",
        "captured_at": (hero_det.visit.started_at if hero_det.visit else hero_det.created_at).isoformat(),
        "reason": "Highest visual clarity and confidence today",
    }

    return {
        "date": target.isoformat(),
        "is_today": is_today,
        "has_data": True,
        "fallback_date": fallback_date,
        "total_visits": len({d.visit_id for d in dets}),
        "total_detections": len(dets),
        "species_count": len(species_map),
        "hero": hero_dict,
        "species_highlights": highlights,
    }


@router.get("/visits/{visit_id}")
async def get_visit(visit_id: int, db: Session = Depends(get_db)) -> dict:
    visit = (
        db.query(Visit)
        .options(joinedload(Visit.detections).joinedload(Detection.species))
        .filter(Visit.id == visit_id)
        .one()
    )
    return {
        "id": visit.id,
        "started_at": visit.started_at.isoformat(),
        "ended_at": visit.ended_at.isoformat() if visit.ended_at else None,
        "clip_url": f"/media/{visit.clip_path}" if visit.clip_path else None,
        "detections": [
            {
                "id": d.id,
                "species": d.species.common_name if d.species else None,
                "confidence": d.confidence,
                "sex": d.sex,
                "is_pair": any(
                    o.id != d.id and o.species_id == d.species_id and o.sex and d.sex and o.sex != d.sex
                    for o in visit.detections
                ),
                "audio_confirmed": bool(d.audio_confirmed),
                "crop_url": f"/media/{d.crop_path}",
                "track_id": d.track_id,
                "has_lucky": bool(
                    d.visit_id is not None
                    and d.track_id is not None
                    and (CROPS_DIR / f"v{d.visit_id:08d}_t{d.track_id:04d}_initial_raw.jpg").exists()
                ),
                "has_sr": bool(
                    d.visit_id is not None
                    and d.track_id is not None
                    and (CROPS_DIR / f"v{d.visit_id:08d}_t{d.track_id:04d}_sr.jpg").exists()
                ),
                "has_sisr": bool(
                    d.visit_id is not None
                    and d.track_id is not None
                    and (CROPS_DIR / f"v{d.visit_id:08d}_t{d.track_id:04d}_sisr.jpg").exists()
                ),
            }
            for d in visit.detections
        ],
    }


@router.get("/{detection_id}/crop")
async def get_detection_crop(
    detection_id: int,
    chroma: bool | None = Query(None, description="Apply chroma-guided filtering (4:2:0 subsampling restoration)"),
    clahe: bool | None = Query(None, description="Apply CLAHE dynamic range normalization"),
    mertens: bool | None = Query(None, description="Apply Mertens multiscale exposure fusion"),
    sharpen: bool | None = Query(None, description="Apply edge-preserving bilateral unsharp masking"),
    sr: bool | None = Query(None, description="Apply 2x multi-frame shift-and-add super-resolution"),
    sisr: bool | None = Query(None, description="Apply 2x single-image neural super-resolution (FSRCNN)"),
    bokeh: bool | None = Query(None, description="Apply synthetic bokeh background defocus"),
    preset: str | None = Query(None, description="Convenience preset: 'raw', 'polish', 'bokeh', 'bokeh_only', 'mertens_hdr', 'mertens_only', 'super_res', 'super_res_only', 'neural_sr', 'neural_sr_only', 'chroma_only', 'clahe_only', 'sharpen_only'"),
    source: str = Query("lucky", description="'lucky' (default) or 'initial' (pre-lucky 3fps frame)"),
    db: Session = Depends(get_db),
):
    """Serve a dynamically rendered computational photography variant of a detection's crop."""
    import cv2
    from pipeline.process import (
        CROPS_DIR,
        DATA_DIR,
        FRAMES_DIR,
        _extract_crop_from_image,
        render_crop_variant,
    )

    detection = db.query(Detection).filter(Detection.id == detection_id).one_or_none()
    if not detection:
        raise HTTPException(status_code=404, detail="Detection not found")

    # Map presets
    if preset == "raw":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, False, False, False, False, False
    elif preset == "polish":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, True, True, True, True, False
    elif preset == "bokeh":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, True, True, True, True, True
    elif preset == "bokeh_only":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, False, False, False, False, True
    elif preset == "mertens_hdr":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, True, False, True, True, False
    elif preset == "mertens_only":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, False, False, True, False, False
    elif preset == "super_res":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = True, False, True, True, True, True, False
    elif preset == "super_res_only":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = True, False, False, False, False, False, False
    elif preset == "neural_sr":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, True, True, True, True, True, False
    elif preset == "neural_sr_only":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, True, False, False, False, False, False
    elif preset == "chroma_only":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, True, False, False, False, False
    elif preset == "clahe_only":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, False, True, False, False, False
    elif preset == "sharpen_only":
        use_sr, use_sisr, use_chroma, use_clahe, use_mertens, use_sharpen, use_bokeh = False, False, False, False, False, True, False
    else:
        use_sr = sr if sr is not None else False
        use_sisr = sisr if sisr is not None else False
        use_chroma = chroma if chroma is not None else True
        use_clahe = clahe if clahe is not None else True
        use_mertens = mertens if mertens is not None else True
        use_sharpen = sharpen if sharpen is not None else True
        use_bokeh = bokeh if bokeh is not None else False
    def _render() -> bytes:
        raw_crop = None
        sr_path = None
        sisr_path = None

        # 0. If super_res requested and pre-saved _sr.jpg exists on disk, use it directly
        if use_sr:
            sr_path = CROPS_DIR / f"v{vid:08d}_t{tid:04d}_sr.jpg"
            if sr_path.exists():
                raw_crop = cv2.imread(str(sr_path))
        elif use_sisr:
            sisr_path = CROPS_DIR / f"v{vid:08d}_t{tid:04d}_sisr.jpg"
            if sisr_path.exists():
                raw_crop = cv2.imread(str(sisr_path))

        # 1. If source == "initial", check if pre-lucky initial raw crop exists
        if source == "initial":
            init_path = CROPS_DIR / f"v{vid:08d}_t{tid:04d}_initial_raw.jpg"
            if init_path.exists():
                raw_crop = cv2.imread(str(init_path))

        # 2. Check standard raw crop file on disk
        if raw_crop is None:
            raw_path = CROPS_DIR / f"v{vid:08d}_t{tid:04d}_raw.jpg"
            if raw_path.exists():
                raw_crop = cv2.imread(str(raw_path))

        # 3. Check source frame to extract raw crop on-demand
        if raw_crop is None:
            frame_path = FRAMES_DIR / f"v{vid:08d}_t{tid:04d}.jpg"
            if frame_path.exists() and bbox:
                frame = cv2.imread(str(frame_path))
                if frame is not None:
                    class _BboxHolder:
                        def __init__(self, b):
                            self.bbox = b

                    raw_crop = _extract_crop_from_image(_BboxHolder(bbox), frame)
                    if raw_crop is not None and raw_crop.size > 0:
                        # Cache to crops/ so future variant requests never re-decode 4K frames
                        cv2.imwrite(str(CROPS_DIR / f"v{vid:08d}_t{tid:04d}_raw.jpg"), raw_crop, [cv2.IMWRITE_JPEG_QUALITY, 95])

        # 4. Fallback to existing saved crop
        if raw_crop is None and crop_path_val:
            saved_crop_path = DATA_DIR / crop_path_val
            if saved_crop_path.exists():
                raw_crop = cv2.imread(str(saved_crop_path))

        if raw_crop is None or raw_crop.size == 0:
            return b""

        # If super_res was requested but no pre-saved _sr.jpg existed, compute 2x super-res on the fly
        if use_sr and (sr_path is None or not sr_path.exists()):
            raw_crop = render_crop_variant(
                raw_crop,
                super_res=True,
                chroma=False,
                clahe=False,
                mertens=False,
                sharpen=False,
            )
        elif use_sisr and (sisr_path is None or not sisr_path.exists()):
            raw_crop = render_crop_variant(
                raw_crop,
                sisr=True,
                chroma=False,
                clahe=False,
                mertens=False,
                sharpen=False,
            )

        rendered = render_crop_variant(
            raw_crop,
            chroma=use_chroma,
            clahe=use_clahe,
            mertens=use_mertens,
            sharpen=use_sharpen,
            bokeh=use_bokeh,
        )

        ok, buf = cv2.imencode(".jpg", rendered, [cv2.IMWRITE_JPEG_QUALITY, 92])
        if not ok:
            return b""
        return buf.tobytes()

    vid = detection.visit_id
    tid = detection.track_id
    bbox = detection.bbox
    crop_path_val = detection.crop_path

    content = await run_in_threadpool(_render)
    if not content:
        raise HTTPException(status_code=404, detail="Crop image file not found or failed to render")

    return Response(
        content=content,
        media_type="image/jpeg",
        headers={"Cache-Control": "public, max-age=86400, immutable"},
    )


@router.get("/{detection_id}/crop-variants")
async def get_detection_crop_variants(
    detection_id: int,
    db: Session = Depends(get_db),
):
    """Return metadata and quick URLs for all available crop variants of a detection."""
    from pipeline.process import CROPS_DIR, FRAMES_DIR

    detection = db.query(Detection).filter(Detection.id == detection_id).one_or_none()
    if not detection:
        raise HTTPException(status_code=404, detail="Detection not found")

    vid = detection.visit_id
    tid = detection.track_id
    has_initial = (CROPS_DIR / f"v{vid:08d}_t{tid:04d}_initial_raw.jpg").exists()
    has_sr = (CROPS_DIR / f"v{vid:08d}_t{tid:04d}_sr.jpg").exists()
    has_sisr = (CROPS_DIR / f"v{vid:08d}_t{tid:04d}_sisr.jpg").exists()
    has_raw = (
        (CROPS_DIR / f"v{vid:08d}_t{tid:04d}_raw.jpg").exists()
        or (FRAMES_DIR / f"v{vid:08d}_t{tid:04d}.jpg").exists()
    )

    base = f"/api/detections/{detection_id}/crop"
    variants = {
        "polish": f"{base}?preset=polish",
        "bokeh": f"{base}?preset=bokeh",
        "bokeh_only": f"{base}?preset=bokeh_only",
        "mertens_hdr": f"{base}?preset=mertens_hdr",
        "super_res": f"{base}?preset=super_res",
        "super_res_only": f"{base}?preset=super_res_only",
        "neural_sr": f"{base}?preset=neural_sr",
        "neural_sr_only": f"{base}?preset=neural_sr_only",
        "mertens_only": f"{base}?preset=mertens_only",
        "raw": f"{base}?preset=raw",
        "chroma_only": f"{base}?preset=chroma_only",
        "clahe_only": f"{base}?preset=clahe_only",
        "sharpen_only": f"{base}?preset=sharpen_only",
    }
    if has_initial:
        variants["initial_raw"] = f"{base}?preset=raw&source=initial"
        variants["initial_polish"] = f"{base}?preset=polish&source=initial"

    return {
        "detection_id": detection_id,
        "has_raw": has_raw,
        "has_initial": has_initial,
        "has_sr": has_sr,
        "has_sisr": has_sisr,
        "sharpness": detection.sharpness,
        "crop_area_px": detection.crop_area_px,
        "brightness": detection.brightness,
        "variants": variants,
    }

