"""Read-side API used by the PWA."""
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import and_, desc, or_, select
from sqlalchemy.orm import Session, joinedload

from db.models import (
    NOT_A_BIRD_LABEL,
    POOR_QUALITY_LABEL,
    SENTINEL_LABELS,
    Correction,
    Detection,
    Species,
    Visit,
)

# Sentinels we hide from the default feed: things the user has explicitly
# said are not real-bird-sightings the feed should surface. NAB (false
# positive) and Poor Quality (unidentifiable crop) both retire the row
# from the browsing view. Unknown bird is intentionally NOT here — it
# IS a real bird, just species-unspecified, and the user wants to see
# it in the feed.
HIDDEN_FROM_FEED = frozenset({NOT_A_BIRD_LABEL, POOR_QUALITY_LABEL})
from db.session import get_db

router = APIRouter()


def _parse_cursor(cursor: str) -> tuple[datetime, int]:
    """Decode a 'captured_at_iso|detection_id' cursor string."""
    try:
        ts_str, id_str = cursor.split("|", 1)
        return datetime.fromisoformat(ts_str), int(id_str)
    except (ValueError, AttributeError) as exc:
        raise HTTPException(status_code=400, detail=f"Invalid cursor: {cursor}") from exc


@router.get("")
async def list_detections(
    limit: int = Query(50, le=200),
    species_id: int | None = Query(None, description="Filter to one species (by id)"),
    species_name: str | None = Query(None, description="Filter to one species (by common name — convenience for the picker which speaks names)"),
    include_not_a_bird: bool = Query(False, description="Include detections corrected to 'Not a bird'"),
    only_not_a_bird: bool = Query(False, description="Show ONLY detections corrected to 'Not a bird' — for reviewing/correcting prior NAB labels"),
    only_unidentified: bool = Query(False, description="Show ONLY detections with no species assigned (the classifier rejected; awaiting user label)"),
    awaiting_review: bool = Query(
        False,
        description="Show ONLY detections the classifier labeled but the user hasn't "
        "reviewed yet — species_id IS NOT NULL and no Correction row exists. Drives the "
        "'Awaiting review' feed filter that measures true positives.",
    ),
    source: str | None = Query(
        None,
        description="Filter to detections whose Correction was generated by this source "
        "(e.g. `llm-claude`). Used by the LLM-review feed to bulk-spot-check Claude's labels.",
    ),
    bad_quality: bool = Query(
        False,
        description="Show ONLY detections flagged as low-quality by any of the "
        "per-crop metrics: small (max bbox dim < 80 px), dark (mean grayscale "
        "< 30), or blurry (Laplacian variance < 30). Compose with other filters "
        "(e.g. awaiting_review=true AND bad_quality=true to triage the worst "
        "candidates first).",
    ),
    min_sharpness: float | None = Query(
        None,
        description="Numeric lower bound on Laplacian-variance sharpness. Use "
        "with a negative sign for the inverse — e.g. set bad_quality=true to get "
        "the standard 'is blurry' threshold of <30, or pass min_sharpness=100 to "
        "see only crisper-than-average crops.",
    ),
    before: str | None = Query(
        None,
        description="Cursor for pagination, format: '<captured_at_iso>|<detection_id>'. "
        "Returns rows captured strictly before this point. The detection id is the "
        "tiebreaker for visits that share a started_at value.",
    ),
    db: Session = Depends(get_db),
) -> list[dict]:
    # Sort by CAPTURE time (Visit.started_at, parsed from the Reolink filename),
    # NOT by processing time (Detection.created_at / id). During a backlog drain
    # these can differ by many hours — an old visit just processed shouldn't pop
    # to the top of the feed. Detection.id desc as a tiebreaker keeps the order
    # deterministic when multiple visits share a started_at second.
    q = (
        db.query(Detection)
        .join(Visit, Detection.visit_id == Visit.id)
        .options(joinedload(Detection.species), joinedload(Detection.visit))
        .order_by(desc(Visit.started_at), desc(Detection.id))
    )
    if species_id is not None:
        q = q.filter(Detection.species_id == species_id)
    if species_name is not None:
        # Resolve name → id once; if no Species row exists yet for this name
        # (the picker can offer names not yet in the DB), return an empty
        # result instead of erroring — semantically "no detections of that".
        sp = db.query(Species).filter(Species.common_name == species_name).one_or_none()
        if sp is None:
            return []
        q = q.filter(Detection.species_id == sp.id)
    if only_unidentified:
        # The "show me the queue I need to label" filter.
        q = q.filter(Detection.species_id.is_(None))
    if only_not_a_bird:
        # NAB-review mode: show ONLY 'Not a bird'-labeled detections so the
        # user can scan past mistakes and re-correct them. include_not_a_bird
        # is ignored in this mode (we're explicitly opting INTO NAB).
        q = q.join(Species, Detection.species_id == Species.id).filter(
            Species.common_name == NOT_A_BIRD_LABEL
        )
    elif not include_not_a_bird:
        # Default feed: hide NAB and Poor-Quality detections so the feed
        # shows only real, identifiable birds. The rows still exist in
        # the DB for the retraining pipeline (NAB as negatives,
        # Poor Quality as explicit drop-from-training samples).
        q = q.outerjoin(Species, Detection.species_id == Species.id).filter(
            (Species.common_name.is_(None))
            | (~Species.common_name.in_(HIDDEN_FROM_FEED))
        )
    if source is not None:
        # Restrict to detections whose LATEST Correction was generated by
        # the given source. Used by the "LLM-labeled" review filter so the
        # user can scan Claude's labels and override the wrong ones.
        #
        # Latest, not any: a detection the user has since corrected or
        # confirmed grows a newer Correction row, and the older LLM row —
        # where pre-retire-mechanism legacy data still has one — must not
        # drag the detection back into the review queue. This must stay in
        # lockstep with the corrections_by_det pick below, which is what
        # the card UI keys its review affordances on.
        latest_correction_source = (
            select(Correction.source)
            .where(Correction.detection_id == Detection.id)
            .order_by(Correction.created_at.desc(), Correction.id.desc())
            .limit(1)
            .scalar_subquery()
        )
        q = q.filter(latest_correction_source == source)
    if bad_quality:
        # "Bad crop" filter: any of the three quality dimensions trips.
        # Thresholds (small/dark/blurry) are intentionally lenient — we
        # want to surface the rough triage pool, not a precise rejection
        # set. Min-quality compositions (min_sharpness etc.) are the more
        # precise tool. NULL values on legacy rows are NOT flagged as bad
        # (no quality info means "unknown," don't surface accidentally).
        q = q.filter(or_(
            Detection.crop_area_px < 80 * 80,
            Detection.brightness < 30,
            Detection.sharpness < 30,
        ))
    if min_sharpness is not None:
        q = q.filter(Detection.sharpness >= min_sharpness)
    if awaiting_review:
        # Classifier produced a label, user hasn't acted on it yet.
        # We can't measure true-positive rate without this — every
        # Correction today is implicitly "user disagreed," so the
        # classifier_accuracy metric is selection-biased to ~0%. This
        # filter surfaces the unreviewed pool so the user can ✓ Confirm
        # (records agreement) or ✏️ Change / 🚫 NAB (existing paths).
        q = q.outerjoin(Correction, Correction.detection_id == Detection.id).filter(
            Detection.species_id.isnot(None),
            Correction.id.is_(None),
        )
    if before is not None:
        # Compound cursor: row "comes before" the cursor iff its (started_at, id)
        # is lexicographically smaller in our DESC ordering.
        cur_ts, cur_id = _parse_cursor(before)
        q = q.filter(
            or_(
                Visit.started_at < cur_ts,
                and_(Visit.started_at == cur_ts, Detection.id < cur_id),
            )
        )
    rows = q.limit(limit).all()

    # Look up Correction.{source,rationale} for each detection in the page
    # in one shot — we want to surface a small "✨ Claude says: ..." line
    # on the card whenever the label came from an LLM. We don't join in
    # the SQL above because the user can disable the source filter and
    # still want this metadata.
    det_ids = [d.id for d in rows]
    corrections_by_det: dict[int, Correction] = {}
    if det_ids:
        for c in db.query(Correction).filter(Correction.detection_id.in_(det_ids)).all():
            # If a detection somehow has multiple Correction rows (shouldn't
            # in normal use, but the model allows it), prefer the most
            # recent — that's what the picker UI would also have written.
            # Same (created_at, id) ordering as the source-filter subquery
            # above — the two must agree on which Correction is "current".
            existing = corrections_by_det.get(c.detection_id)
            if existing is None or (
                (c.created_at or datetime.min, c.id)
                > (existing.created_at or datetime.min, existing.id)
            ):
                corrections_by_det[c.detection_id] = c

    return [
        {
            "id": d.id,
            "visit_id": d.visit_id,
            # species_id lets the PWA link cards to the /species/:id plate.
            "species_id": d.species_id,
            "species": d.species.common_name if d.species else None,
            "scientific_name": d.species.scientific_name if d.species else None,
            # Wikipedia thumbnail surfaced on review-mode cards so the user
            # can compare their crop against a clean reference photo. NULL
            # for sentinels / families / un-fetched species.
            "reference_image_url": d.species.reference_image_url if d.species else None,
            "confidence": d.confidence,
            "audio_confirmed": bool(d.audio_confirmed),
            "raw_predictions": d.raw_predictions,
            "crop_url": f"/media/{d.crop_path}",
            "bbox": d.bbox,
            "track_id": d.track_id,
            "captured_at": d.visit.started_at.isoformat() if d.visit else d.created_at.isoformat(),
            "created_at": d.created_at.isoformat(),
            "cursor": f"{(d.visit.started_at if d.visit else d.created_at).isoformat()}|{d.id}",
            # New fields for spot-checking LLM-generated labels. Both
            # null on legacy / user-via-UI corrections.
            "correction_source": (corrections_by_det.get(d.id).source if corrections_by_det.get(d.id) else None),
            "correction_rationale": (corrections_by_det.get(d.id).rationale if corrections_by_det.get(d.id) else None),
            # Per-crop quality metrics. NULL on legacy rows that haven't
            # been backfilled. Frontend uses these for the per-card score
            # footer and the "bad crops" filter chip.
            "crop_area_px": d.crop_area_px,
            "brightness": d.brightness,
            "sharpness": d.sharpness,
        }
        for d in rows
    ]


@router.get("/visits/{visit_id}")
async def get_visit(visit_id: int, db: Session = Depends(get_db)) -> dict:
    visit = (
        db.query(Visit)
        .options(joinedload(Visit.detections).joinedload(Detection.species))
        .filter(Visit.id == visit_id)
        .one()
    )
    return {
        "id": visit.id,
        "started_at": visit.started_at.isoformat(),
        "ended_at": visit.ended_at.isoformat() if visit.ended_at else None,
        "clip_url": f"/media/{visit.clip_path}" if visit.clip_path else None,
        "detections": [
            {
                "id": d.id,
                "species": d.species.common_name if d.species else None,
                "confidence": d.confidence,
                "audio_confirmed": bool(d.audio_confirmed),
                "crop_url": f"/media/{d.crop_path}",
                "track_id": d.track_id,
            }
            for d in visit.detections
        ],
    }
