"""SQLite session management."""
import logging
from pathlib import Path

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import DeclarativeBase, sessionmaker

log = logging.getLogger(__name__)

DB_PATH = Path(__file__).parent.parent / "data" / "birdwatcher.db"
DB_PATH.parent.mkdir(exist_ok=True)

engine = create_engine(
    f"sqlite:///{DB_PATH}",
    connect_args={"check_same_thread": False},
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


# Lightweight, idempotent additive-column migrations. We don't run Alembic
# because the schema is small and the DB is one SQLite file; adding columns
# in code keeps deploys to a single rsync+up. The trade-off is we have to
# remember to list every new column here. Tuples are (table, column, sql_type).
_ADDITIVE_COLUMNS = [
    ("detections", "yolo_confidence", "REAL"),
    # Track-history bboxes for the size-prior smoothing experiment. NULL
    # for rows written before the column existed; populated by
    # pipeline/process.py for new detections.
    ("detections", "track_bboxes", "JSON"),
    # Per-visit count of YOLO detections suppressed by the scene mask.
    # Surfaces an invisible funnel stage on the Stats page.
    ("visits", "scene_mask_suppressed", "INTEGER"),
    # Daily aggregate of the per-visit column above.
    ("pipeline_stats_daily", "detections_scene_mask_suppressed", "INTEGER"),
    # Marker for family-level catch-all Species rows ("Sparrow", "Warbler").
    ("species", "is_family", "INTEGER"),
    # Provenance for Correction rows. NULL = user-via-UI; "llm-claude"
    # for ones generated by scripts/llm_classify_unidentified.py.
    ("corrections", "source", "TEXT"),
    # One-line "why this label" for non-NULL source (e.g., Claude's
    # vision-model rationale for each LLM-generated correction).
    ("corrections", "rationale", "TEXT"),
    # Wikipedia thumbnail for the species, surfaced in the review-mode
    # cards so the user can compare their crop against a clean photo.
    ("species", "reference_image_url", "TEXT"),
    ("species", "reference_image_checked_at", "DATETIME"),
    # Crop-quality metrics populated at ingest in pipeline/process.py.
    # Drive the "bad crops" feed filter and feed training-data quality
    # gates in the next birdclass-na retrain. NULL for rows written
    # before this column existed; backfilled by
    # scripts/backfill_crop_quality.py.
    ("detections", "crop_area_px", "INTEGER"),
    ("detections", "brightness", "REAL"),
    ("detections", "sharpness", "REAL"),
]


def _apply_additive_migrations() -> None:
    """ALTER TABLE ADD COLUMN for any column listed in _ADDITIVE_COLUMNS
    that isn't already present. Existing rows get NULL — the model marks
    the column nullable so this is fine."""
    insp = inspect(engine)
    with engine.begin() as conn:
        for table, col, sql_type in _ADDITIVE_COLUMNS:
            if not insp.has_table(table):
                continue  # create_all will handle fresh DBs
            existing = {c["name"] for c in insp.get_columns(table)}
            if col in existing:
                continue
            log.info("Migration: ALTER TABLE %s ADD COLUMN %s %s", table, col, sql_type)
            conn.execute(text(f"ALTER TABLE {table} ADD COLUMN {col} {sql_type}"))


def init_db() -> None:
    # Importing models triggers table registration on Base.metadata
    from db import models  # noqa: F401

    Base.metadata.create_all(bind=engine)
    _apply_additive_migrations()

    # Seed family-level catch-all Species rows. Idempotent — running on
    # every boot is fine (just a couple of unique-name lookups).
    from db.families import ensure_family_species_rows
    seed_db = SessionLocal()
    try:
        created = ensure_family_species_rows(seed_db)
        if created:
            log.info("Seeded %d family-level Species row(s)", created)
    except Exception:
        log.exception("Failed to seed family Species rows")
    finally:
        seed_db.close()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
