#!/usr/bin/env bash
# deploy_to_server.sh — runs FROM your Mac to push the current repo state
# (including the gitignored .env) to a remote BirdWatcher VM and invoke
# scripts/bootstrap_server.sh there.
#
# Usage:
#   scripts/deploy_to_server.sh ryan@birdwatcher.ryanhoulette.com
#
# Idempotent — re-runs sync changes and rebuild whatever changed.

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <user>@<host>" >&2
  exit 2
fi

TARGET="$1"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

cd "$REPO_ROOT"

if [ ! -f backend/.env ]; then
  echo "Refusing to deploy: backend/.env is missing. Create it from .env.example first." >&2
  exit 1
fi

echo "Syncing repo to $TARGET:~/BirdWatcher/ …"
# Notes on exclusions:
#   - .git is intentionally synced so the remote can see commit hashes if needed.
#   - node_modules and .venv are huge and host-specific; rebuilt on the remote.
#   - backend/data and backend/models are runtime artifacts; remote builds them.
#   - frontend/dist is rebuilt on remote.
#   - backend/secrets/ MUST be excluded: it holds vapid_private.pem on the
#     remote, generated by the first deploy. Without this exclusion --delete-
#     after would wipe the key on every deploy and force every push
#     subscription to re-register from scratch.
ssh "$TARGET" "mkdir -p ~/BirdWatcher"
# --no-perms / --no-owner / --no-group avoid the "partial transfer due to
# vanished files" (exit 23) race that aborts `set -e` deploys when local
# sweep output rotates mid-transfer. The bootstrap step that rebuilds the
# frontend and the API image is the important part — losing it because a
# stale build artifact disappeared between rsync's enumeration and copy
# phases is a regular footgun.
RSYNC_RC=0
rsync -avz --delete-after \
  --exclude='.venv/' \
  --exclude='node_modules/' \
  --exclude='backend/data/' \
  --exclude='backend/data.real-backup/' \
  --exclude='backend/models/' \
  --exclude='backend/secrets/' \
  --exclude='backend/scripts/sweep/data/' \
  --exclude='backend/scripts/sweep/results/' \
  --exclude='backend/yolo*.pt' \
  --exclude='frontend/dist/' \
  --exclude='__pycache__/' \
  --exclude='.pytest_cache/' \
  --exclude='*.pyc' \
  --exclude='.DS_Store' \
  --exclude='/.env' \
  ./ "$TARGET:~/BirdWatcher/" || RSYNC_RC=$?
# Treat "vanished files" (24) and "partial transfer" (23) as soft — the
# subsequent bootstrap step is what matters; hard-fail on anything else.
if [ "$RSYNC_RC" -ne 0 ] && [ "$RSYNC_RC" -ne 23 ] && [ "$RSYNC_RC" -ne 24 ]; then
  echo "rsync failed with code $RSYNC_RC" >&2
  exit "$RSYNC_RC"
fi

# Note on /.env: that's the project-root .env which bootstrap_server.sh
# generates on the remote (as a mirror of backend/.env) so docker compose's
# YAML interpolation resolves correctly. We exclude it from rsync so a
# stray local copy can't clobber the authoritative remote one mid-deploy.

echo "Invoking bootstrap on $TARGET …"
ssh "$TARGET" "cd ~/BirdWatcher && bash scripts/bootstrap_server.sh"

# Pull the (possibly patched) .env back to local so the VAPID_PUBLIC_KEY
# stays in sync. The next deploy will then rsync that value up rather than
# clobbering it with an empty local one.
echo "Pulling .env back from $TARGET so local matches remote …"
scp -q "$TARGET:~/BirdWatcher/backend/.env" ./backend/.env

echo "Deploy complete."
