#!/usr/bin/env bash
# deploy_to_server.sh — runs FROM your Mac to push the current repo state
# (including the gitignored .env) to a remote BirdWatcher VM and invoke
# scripts/bootstrap_server.sh there.
#
# Usage:
#   scripts/deploy_to_server.sh ryan@birdwatcher.ryanhoulette.com
#
# Idempotent — re-runs sync changes and rebuild whatever changed.

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <user>@<host>" >&2
  exit 2
fi

TARGET="$1"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

cd "$REPO_ROOT"

if [ ! -f backend/.env ]; then
  echo "Refusing to deploy: backend/.env is missing. Create it from .env.example first." >&2
  exit 1
fi

echo "Syncing repo to $TARGET:~/BirdWatcher/ …"
# Notes on exclusions:
#   - .git is intentionally synced so the remote can see commit hashes if needed.
#   - node_modules and .venv are huge and host-specific; rebuilt on the remote.
#   - backend/data and backend/models are runtime artifacts; remote builds them.
#   - frontend/dist is rebuilt on remote.
#   - backend/secrets/ MUST be excluded: it holds vapid_private.pem on the
#     remote, generated by the first deploy. Without this exclusion --delete-
#     after would wipe the key on every deploy and force every push
#     subscription to re-register from scratch.
ssh "$TARGET" "mkdir -p ~/BirdWatcher"
rsync -avz --delete-after \
  --exclude='.venv/' \
  --exclude='node_modules/' \
  --exclude='backend/data/' \
  --exclude='backend/models/' \
  --exclude='backend/secrets/' \
  --exclude='frontend/dist/' \
  --exclude='__pycache__/' \
  --exclude='.pytest_cache/' \
  --exclude='*.pyc' \
  --exclude='.DS_Store' \
  ./ "$TARGET:~/BirdWatcher/"

echo "Invoking bootstrap on $TARGET …"
ssh "$TARGET" "cd ~/BirdWatcher && bash scripts/bootstrap_server.sh"

# Pull the (possibly patched) .env back to local so the VAPID_PUBLIC_KEY
# stays in sync. The next deploy will then rsync that value up rather than
# clobbering it with an empty local one.
echo "Pulling .env back from $TARGET so local matches remote …"
scp -q "$TARGET:~/BirdWatcher/backend/.env" ./backend/.env

echo "Deploy complete."
